default_stages: [commit]
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
      - id: golangci-lint
        args:
          - "--timeout=5m"
